version: '3.8'

services:
  api:
    container_name: bdda_api
    build: .
    command: sh -c 'yoyo list --database postgresql://postgres:postgres@postgreSQL/postgres; yoyo apply --database postgresql://postgres:postgres@postgreSQL/postgres --batch; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgreSQL
      - redis
      - mongodb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgreSQL
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://mongodb:27017
    networks:
      - app_network

  postgreSQL:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - app_network
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - app_network
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/var/lib/mongodb/data/db
    networks:
      - app_network


volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  app_network: